author: Rainboy
title: Rbook
url: /
#cover: https://ww1.sinaimg.cn/large/007i4MEmgy1fzdgx5suh8j315o0dw4qp.jpg
cover: https://ww1.sinaimg.cn/large/007i4MEmgy1fzf2b74ks0g30kw068jvf.jpg

description: Rbook,Rainboy写的关于Noi的电子书


# GIT配置相关
book_path: xxx
# git 书的地址
# 参考 https://www.cnblogs.com/52cik/p/git-https.html
git_book_hub: xxxx
# 触发的token
token: mytoken

redis: redis://localhost/8  #使用数据库8
# redis 保存的时间 s
redis_key_ttl: 1200



css:
    - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css
    - https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css
    - https://cdnjs.cloudflare.com/ajax/libs/prism/1.15.0/themes/prism-okaidia.min.css
    - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.10.0/katex.min.css
    - https://gitcdn.xyz/repo/sofish/typo.css/master/typo.css
    - /style.light.css
    - /app.css
    - /password.css
    - /codeHighlight.css
    - /codeHighlightCopy.css
    - /github-markdown.css

js:
    - https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js
    - https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js
    - https://unpkg.com/clipboard-polyfill@2.7.0/build/clipboard-polyfill.promise.js
    - https://unpkg.com/viz.js@2.1.2/viz.js
    - https://unpkg.com/viz.js@2.1.2/full.render.js
    - /js/CLIPBOARD.js
    - /js/toggleMenu.js


menu:
    - 
        url: /
        name: 主页
        icon: list-alt
    - 
        url: /about
        name: 关于
        icon: info-circle


## theme 相关
use_header_cover: true


catalog_cover: https://ww1.sinaimg.cn/large/007i4MEmgy1fzeo6efh5ig30lc074tb4.jpg
password_background: https://ww1.sinaimg.cn/large/007i4MEmgy1fzenxp74yig30lc074qlw.jpg
jump_background: https://ww1.sinaimg.cn/large/007i4MEmgy1fzfigktlheg30b4072nlu.jpg
#jump_background: https://ww1.sinaimg.cn/large/007i4MEmgy1fzfhqrx8sqg30kw068448.jpg
